#CAUTION: the following variables need to be defined in
#<<repo>>/settings/variables/actions
#NEO4J_URL: e.g. neo4j+s://xxxxx.databases.neo4j.io:7687
#NEO4J_USER: e.g. neo4j
#NEO4J_PASSWD: e.g. secret
#SCRIPTS_DIR: e.g. PythonScripts2023 has to match your folder structure
#MY_ISSUE_LABEL: e.g. Survey for Local language workflows 2023

name: Local Languages Survey 2023 GitHub Actions workflow
run-name: Local Languages 2023 GitHub Actions
on:
  issues: 
    types: [opened, edited]

jobs:
  issue_opened_edited:
    runs-on: self-hosted
    steps:
      - name: Print issue details
        run: |
          echo Gotcha issue $LABELS
        env:
          LABELS: ${{ github.event.issue.labels[0].name }}

      - name: Checkout so that we have the python script in the container
        uses: actions/checkout@v2
        with:
          repository: pavankumar0077/Local-Language-for-Workflows
          token: ${{ secrets.GIT_TOKEN }}

      - name: View the github context
        run: echo "$GITHUB_CONTEXT" >> ${{ vars.SCRIPTS_DIR }}/issue.out
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Install Python and Neo4j
        run: |
          python3 -m pip install --upgrade pip
          pip install neo4j
          python3 ${{ vars.SCRIPTS_DIR }}/PushRecordToNeo4j.py
        env:
          NEO4J_URI: ${{ vars.NEO4J_URL }}  # Add the secret for your local server URI
          NEO4J_USER: ${{ vars.NEO4J_USER }}  # Add the secret for your local server username
          NEO4J_PASSWD: ${{ vars.NEO4J_PASSWD }}  # Add the secret for your local server password
          SCRIPTS_DIR: ${{ vars.SCRIPTS_DIR }}
          MY_ISSUE_LABEL: ${{ vars.MY_ISSUE_LABEL }}

